version: 2.1

jobs:
  hello-world:
    docker:
      - image: cimg/node:18.12.1
    steps:
      - run: echo 'Hello World'

workflows:
  cicd:
    jobs:
      - hello-world

# VS Code Extension Version: 1.5.1